### ISSUE TITLE
关于output目录生成问题

### ISSUE THREAD

**Issue by simonlify** [xiaoyann/webpack-react-redux-es6-boilerplate#2]
你好，我之前问过你几个此项目的问题，现在我又有新问题了，已经研究了大半天，没有搞明白，问题如下：
     之前我想借用你这套框架在做自己的项目，经过几番周折，现在已进入编程阶段，我也学着最后的打包工作，从我的理解来看，output里面配置的应该就是打包后的项目文件，可是我执行npm start
本地项目可以直接运行，但是文件没有生成，后来查到，命令 webpack -d / -p 可以生成编译打包后的目录，但是貌似在我这里没有任何效果，我能确定的是配置路径没有任何错误。
望解答，谢谢！

**Comment by xiaoyann** [comment]
1. npm start 用的是开发环境，不会生成文件
2. npm run release 产出生产环境文件
