### ISSUE TITLE
为何不引入webpack DLL

### ISSUE THREAD

**Issue by crper** [xiaoyann/webpack-react-redux-es6-boilerplate#3]
[彻底解决Webpack打包性能问题](https://zhuanlan.zhihu.com/p/21748318)

**Comment by xiaoyann** [comment]
可以使用 DLL，这里只是个示例项目，我在对应的文章中也提到了使用 DLL 解决 hash 问题，另外使用  DLL 需要额外做几件事，虽然也比较简单：
1. 维护 DLL 配置文件
2. 另外做些处理能将 DLL 文件自动放入到 HTML 页面
3. DLL 文件需要可以访问，结合开发环境
