### ISSUE TITLE
关于页面刷新的问题

### ISSUE THREAD

**Issue by simonlify** [xiaoyann/webpack-react-redux-es6-boilerplate#4]
你的这个demo我发现有个问题，打包后，路径切到dist目录下，运行起来！
我运行起来后，比如url是http://localhost:8000 
项目可以正常运行，当我点击page2的时候，url为 http://localhost:8000/page2
此时，刷新页面，就变404了 实际上任何非http://localhost:8000 的url都报404.
请问，这是为什么？？？可有解决办法？

**Comment by xiaoyann** [comment]
这个项目使用的 BrowserHistory，需要服务器支持，webpack-dev-server 是支持的，所以没问题，如果服务器不支持，你应该切换到 HashHistory。http://react-guide.github.io/react-router-cn/docs/guides/basics/Histories.html#createbrowserhistory

**Comment by simonlify** [comment]
嗯，我也找到了问题所在
https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#configuring-your-server
感谢！
