### ISSUE TITLE
关于图片打包的问题

### ISSUE THREAD

**Issue by simonlify** [xiaoyann/webpack-react-redux-es6-boilerplate#5]
I am back again!!
你好，我的问题如下：

// // 图片路径处理，压缩
config.module.loaders.push({
  test: /.(?:jpg|gif|png|svg)$/,
  loaders: [
    'url?limit=25000&name=img/[hash].[ext]',
    'image-webpack'
  ]
});

在webpack.config.js中，这段代码用于检测项目中图片大小，重新命名，并根据我设置的limit值做base64编码，然后通过image-webpack-loader去压缩，在mac os系统下，一切运行正常
但是在linux环境下运行，如果加上image-wepack，图片没有做合并，我这边运行的效果是，根目录执行npm start ,项目中所有用到的图片，都会以重命名后的文件出现在根目录下，如果我不加image-wepack则不会出现这样的情况，但是发布出来的文件就比较大

我的linux系统 
uname -a 出来的信息是：Linux 02fd0bed9712 4.4.16-moby #1 SMP Tue Aug 9 17:20:17 UTC 2016 x86_64 GNU/Linux

我已经花了半天多的时间，没找到解决办法，不知道这个问题你是否碰到过，能否给点理论上的建议？？

**Comment by xiaoyann** [comment]
你的意思是在 linux 下 image-webpack 没有压缩图片？

**Comment by simonlify** [comment]
对的，而且我不确定的是，为什么它会把我所有用到的图片，全部生成到根目录下，看起来很混乱

**Comment by xiaoyann** [comment]
mac 下是没问题的，你可以看看 [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader) 的选项，调整一下类似质量的选项，会影响压缩的效果。然后是产出路径，mac 的系统是基于 unix 的，路径处理应该没有差异吧，只能建议你注意下配置文件中关于各种路径的配置项了

**Comment by simonlify** [comment]
好的，谢谢！
