### ISSUE TITLE
npm run release 打包之后出错

### ISSUE THREAD

**Issue by liupeng110112** [xiaoyann/webpack-react-redux-es6-boilerplate#6]
visual.html:formatted:17Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by xiaoyann** [comment]
把 build/webpack.config.js 中的这段代码注释掉：

``` js
// 去掉重复模块
if (!__DEV__) {
  config.plugins.push(
    new webpack.optimize.DedupePlugin()
  );
}
```

**Comment by liupeng110112** [comment]
@xiaoyann  这个模块主要是去除重复模块，具体是什么意思？？

**Comment by xiaoyann** [comment]
重复的文件模块，可能是依赖树比较特殊造成的，不然应该会共享依赖 https://github.com/webpack/docs/wiki/optimization#deduplication
