### ISSUE TITLE
mac下一切正常，windows下

### ISSUE THREAD

**Issue by ghost** [xiaoyann/webpack-react-redux-es6-boilerplate#7]
> NODE_ENV=development node build/webpack.dev.js --hot

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by ghost** [comment]
更新了下系统,重新git，模块是全的
http://127.0.0.1:8080/
Hash: 39554dba5336e40b66ba
Version: webpack 1.13.2
Time: 2959ms
         Asset       Size  Chunks             Chunk Names
     js/app.js     698 kB    0, 2  [emitted]  app
     js/lib.js     2.5 MB    1, 2  [emitted]  lib
js/manifest.js    24.3 kB       2  [emitted]  manifest
    index.html  323 bytes          [emitted]

ERROR in ./src/pages/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/webpack/buildin/module.js in C:\Users\Administrator\Desktop\webpack-react-redux-es6-boilerplate/src\pages
 @ ./src/pages/app.js 1:0-57

ERROR in ./src/css/common.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/css-loader/index.js in C:\Users\Administrator\Desktop\webpack-react-redux-es6-boilerplate/src\css
 @ ./src/css/common.scss 4:14-168 13:2-17:4 14:20-174

ERROR in ./src/css/common.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/style-loader/addStyles.js in C:\Users\Administrator\Desktop\webpack-react-redux-es6-boilerplate/src\css
 @ ./src/css/common.scss 7:13-71

.........

**Comment by xiaoyann** [comment]
我没有 windows 呀。。。要不自己再调调吧 😄

**Comment by ghost** [comment]
我还是用mac吧

**Comment by lengziyu** [comment]
win不可以用？？我报十多个错误，和上面差不多的错误

**Comment by xiaoyann** [comment]
windows 环境下会有问题，我是在 mac 下开发的，但问题应该不难，用 windows 的可以尝试解决下
