### ISSUE TITLE
npm start error！

### ISSUE THREAD

**Issue by OckhamRazor** [xiaoyann/webpack-react-redux-es6-boilerplate#8]
错误如下,列出一项：

``` text
ERROR in ./src/pages/page3/index.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/style-loader/addStyles.js in C:\Users\baobaobao\Desktop\webpack-react-redux-es6-boilerplate-master/src\pages\page3
 @ ./src/pages/page3/index.scss 7:13-74
```

问题貌似出在webpack.config.js中的context:SRC_PATH,
相关问题在stackoverflow上查询了一下，

> http://stackoverflow.com/questions/38094681/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack
> http://stackoverflow.com/questions/38386797/module-not-found-error-cannot-resolve-file-or-directory-import-sass-in-we/38387587#38387587

仍在解决中，等回复！

**Comment by xiaoyann** [comment]
是 windows 吗？

**Comment by OckhamRazor** [comment]
对啊。看了关闭的issue。不知道能支持一下winow么,感觉挺不错的模板，就是现在webpack的问题解决不了，有点头疼

**Comment by xiaoyann** [comment]
好，我改天找个windows看看

**Comment by xiaoyann** [comment]
已修复
