### ISSUE TITLE
三元操作符导致开发环境下文件命名不对

### ISSUE THREAD

**Issue by xuyongtao** [xiaoyann/webpack-react-redux-es6-boilerplate#9]
![image](https://cloud.githubusercontent.com/assets/7931332/19472258/1c185518-9559-11e6-8a8a-e2d69dd8002a.png)

以下加个括号就没有问题

![image](https://cloud.githubusercontent.com/assets/7931332/19472249/0e4650d4-9559-11e6-9d09-42adbeb93f49.png)

**Comment by xuyongtao** [comment]
另外请教一下webpack-dev-server把打包的资源都放在内存，那我要怎么清除原先内存的资源，我把dist目录下的文件删除是不行的

**Comment by xiaoyann** [comment]
为什么要自己清除，那只是临时的，脚本停止了内存里的东西都会清除的

**Comment by xiaoyann** [comment]
上面那个三元运算符加不加括号没区别呀
